//if (!isServer) exitWith {};
params ["_unit", ["_save", false]];
private ["_unitsGL", "_unitsAT", "_unitsAA", "_unitsAR", "_unitsMG", "_unitsMarksman", "_unitsSniper", "_unitsCrew", "_unitsSpecial", "_unitsRifleman", "_unitsRiflemanLight", "_classMatch"];

diag_log "REMOTEEXEC: started loadout swap on server";
_unitsGL = [
"rhsusf_army_ucp_grenadier",
"rhsusf_army_ucp_riflemanat",
"rhsusf_army_ucp_arb_grenadier",
"rhsusf_army_ucp_arb_riflemanat",
"rhsusf_army_ocp_grenadier",
"rhsusf_army_ocp_riflemanat",
"rhsusf_army_ocp_arb_grenadier",
"rhsusf_army_ocp_arb_riflemanat",
"rhsusf_socom_marsoc_cso_grenadier",
"rhsusf_usmc_marpat_wd_grenadier",
"rhsusf_usmc_marpat_d_grenadier",
"rhsusf_usmc_marpat_d_rifleman_law",
"rhsusf_usmc_marpat_d_riflemanat",
"rhsusf_usmc_marpat_wd_rifleman_law",
"rhsusf_usmc_lar_marpat_d_riflemanat",
"rhsusf_usmc_recon_marpat_d_rifleman_at",
"rhsusf_usmc_recon_marpat_d_rifleman_at_fast",
"rhsusf_usmc_recon_marpat_d_rifleman_at_lite",
"rhsusf_usmc_marpat_wd_riflemanat",
"rhsusf_usmc_recon_marpat_wd_rifleman_at",
"rhsusf_usmc_lar_marpat_wd_riflemanat",
"rhsusf_usmc_recon_marpat_wd_rifleman_at_lite",
"rhsusf_usmc_recon_marpat_wd_rifleman_at_fast"
];

_unitsAT = [
"rhsusf_army_ucp_javelin",
"rhsusf_army_ocp_javelin",
"rhsusf_usmc_marpat_d_javelin",
"rhsusf_usmc_marpat_wd_javelin",
"rhsusf_usmc_marpat_wd_smaw",
"rhsusf_usmc_marpat_d_smaw"
];

_unitsAA = [
"rhsusf_army_ucp_aa",
"rhsusf_army_ocp_aa",
"rhsusf_usmc_marpat_d_stinger",
"rhsusf_usmc_marpat_wd_stinger"
];

_unitsAR = [
"rhsusf_army_ucp_autoriflemana",
"rhsusf_army_ucp_autorifleman",
"rhsusf_army_ucp_arb_autoriflemana",
"rhsusf_army_ucp_arb_autorifleman",
"rhsusf_army_ocp_autoriflemana",
"rhsusf_army_ocp_autorifleman",
"rhsusf_army_ocp_arb_autoriflemana",
"rhsusf_army_ocp_arb_autorifleman",
"rhsusf_usmc_marpat_d_autorifleman_m249_ass",
"rhsusf_usmc_marpat_d_autorifleman_m249",
"rhsusf_usmc_marpat_d_autorifleman",
"rhsusf_usmc_recon_marpat_d_machinegunner_m249_lite",
"rhsusf_usmc_recon_marpat_d_autorifleman_lite",
"rhsusf_usmc_recon_marpat_d_machinegunner_m249_fast",
"rhsusf_usmc_recon_marpat_d_autorifleman_fast",
"rhsusf_usmc_recon_marpat_d_machinegunner_m249",
"rhsusf_usmc_recon_marpat_d_autorifleman",
"rhsusf_usmc_lar_marpat_d_autorifleman",
"rhsusf_usmc_marpat_wd_autorifleman_m249_ass",
"rhsusf_usmc_marpat_wd_autorifleman_m249",
"rhsusf_usmc_marpat_wd_autorifleman",
"rhsusf_usmc_recon_marpat_wd_machinegunner_m249_lite",
"rhsusf_usmc_lar_marpat_wd_autorifleman",
"rhsusf_usmc_recon_marpat_wd_autorifleman_lite",
"rhsusf_usmc_recon_marpat_wd_machinegunner_m249_fast",
"rhsusf_usmc_recon_marpat_wd_autorifleman_fast",
"rhsusf_usmc_recon_marpat_wd_machinegunner_m249",
"rhsusf_usmc_recon_marpat_wd_autorifleman"
];

_unitsMG = [
"rhsusf_army_ucp_machinegunnera",
"rhsusf_army_ucp_machinegunner",
"rhsusf_army_ucp_arb_machinegunnera",
"rhsusf_army_ucp_arb_machinegunner",
"rhsusf_army_ocp_machinegunnera",
"rhsusf_army_ocp_machinegunner",
"rhsusf_army_ocp_arb_machinegunner",
"rhsusf_army_ocp_arb_machinegunnera",
"rhsusf_usmc_marpat_d_machinegunner_ass",
"rhsusf_usmc_marpat_d_machinegunner",
"rhsusf_usmc_recon_marpat_d_machinegunner",
"rhsusf_usmc_lar_marpat_d_machinegunner",
"rhsusf_usmc_marpat_wd_machinegunner",
"rhsusf_usmc_recon_marpat_wd_machinegunner",
"rhsusf_usmc_lar_marpat_wd_machinegunner",
"rhsusf_usmc_marpat_wd_machinegunner_ass"
];

_unitsMarksman = [
"rhsusf_army_ucp_marksman",
"rhsusf_army_ucp_arb_marksman",
"rhsusf_army_ocp_marksman",
"rhsusf_army_ocp_arb_marksman",
"rhsusf_socom_marsoc_spotter",
"rhsusf_usmc_marpat_d_spotter",
"rhsusf_usmc_marpat_d_marksman",
"rhsusf_usmc_lar_marpat_d_marksman",
"rhsusf_usmc_recon_marpat_d_marksman_fast",
"rhsusf_usmc_recon_marpat_d_marksman_lite",
"rhsusf_usmc_marpat_wd_spotter",
"rhsusf_usmc_marpat_wd_marksman",
"rhsusf_usmc_recon_marpat_d_marksman",
"rhsusf_usmc_recon_marpat_wd_marksman_fast",
"rhsusf_usmc_recon_marpat_wd_marksman_lite",
"rhsusf_usmc_recon_marpat_wd_marksman",
"rhsusf_usmc_lar_marpat_wd_marksman"
];

_unitsSniper = [
"rhsusf_army_ucp_sniper_m107",
"rhsusf_army_ucp_sniper_m24sws",
"rhsusf_army_ucp_sniper",
"rhsusf_army_ocp_sniper_m107",
"rhsusf_army_ocp_sniper_m24sws",
"rhsusf_army_ocp_sniper",
"rhsusf_army_ucp_arb_sniper_m107",
"rhsusf_army_ocp_arb_sniper_m107",
"rhsusf_socom_marsoc_sniper_m107",
"rhsusf_socom_marsoc_sniper",
"rhsusf_usmc_marpat_d_sniper_m107",
"rhsusf_usmc_marpat_d_sniper",
"rhsusf_usmc_marpat_wd_sniper_M107",
"rhsusf_usmc_marpat_wd_sniper",
"rhsusf_usmc_recon_marpat_d_sniper_M107",
"rhsusf_usmc_recon_marpat_wd_sniper_M107"
];

_unitsCrew = [
"rhsusf_army_ucp_helicrew",
"rhsusf_army_ucp_helipilot",
"rhsusf_army_ucp_driver_armored",
"rhsusf_army_ucp_driver",
"rhsusf_army_ucp_combatcrewman",
"rhsusf_army_ucp_crewman",
"rhsusf_army_ocp_helicrew",
"rhsusf_army_ocp_driver_armored",
"rhsusf_army_ocp_helipilot",
"rhsusf_army_ocp_driver",
"rhsusf_army_ocp_combatcrewman",
"rhsusf_army_ocp_crewman",
"rhsusf_airforce_pilot",
"rhsusf_airforce_jetpilot",
"rhsusf_socom_swcc_crewman",
"rhsusf_usmc_marpat_d_helicrew",
"rhsusf_usmc_marpat_d_helipilot",
"rhsusf_usmc_marpat_d_gunner",
"rhsusf_usmc_marpat_d_driver",
"rhsusf_usmc_marpat_d_combatcrewman",
"rhsusf_usmc_marpat_d_crewman",
"rhsusf_usmc_lar_marpat_d_combatcrewman",
"rhsusf_usmc_lar_marpat_d_crewman",
"rhsusf_usmc_marpat_wd_helicrew",
"rhsusf_usmc_marpat_wd_helipilot",
"rhsusf_usmc_marpat_wd_gunner",
"rhsusf_usmc_marpat_wd_driver",
"rhsusf_usmc_marpat_wd_combatcrewman",
"rhsusf_usmc_marpat_wd_crewman",
"rhsusf_usmc_lar_marpat_wd_combatcrewman",
"rhsusf_usmc_lar_marpat_wd_crewman"
];

_unitsSpecial = [
"rhsusf_army_ucp_engineer",
"rhsusf_army_ucp_explosives",
"rhsusf_army_ucp_medic",
"rhsusf_army_ucp_uav",
"rhsusf_army_ocp_engineer",
"rhsusf_army_ocp_explosives",
"rhsusf_army_ocp_medic",
"rhsusf_army_ocp_uav",
"rhsusf_socom_mc_uniform",
"rhsusf_socom_g3_m81_uniform",
"rhsusf_socom_g3_tan_uniform",
"rhsusf_socom_g3_rgr_uniform",
"rhsusf_socom_g3_blk_uniform",
"rhsusf_army_ucp_rifleman_m590",
"rhsusf_army_ucp_arb_engineer",
"rhsusf_army_ucp_arb_medic",
"rhsusf_army_ucp_arb_rifleman_m590",
"rhsusf_army_ocp_rifleman_m590",
"rhsusf_army_ocp_arb_engineer",
"rhsusf_army_ocp_arb_medic",
"rhsusf_army_ocp_arb_rifleman_m590",
"rhsusf_navy_sarc_d_fast",
"rhsusf_navy_sarc_w_fast",
"rhsusf_navy_sarc_d",
"rhsusf_navy_sarc_w",
"rhsusf_navy_marpat_d_medic",
"rhsusf_navy_marpat_wd_medic",
"rhsusf_socom_marsoc_sarc",
"rhsusf_socom_marsoc_cso_mechanic",
"rhsusf_socom_marsoc_cso_eod",
"rhsusf_socom_marsoc_cso_breacher",
"rhsusf_assault_eagleaiii_coy_medic",
"rhsusf_usmc_marpat_d_uav",
"rhsusf_usmc_marpat_d_explosives",
"rhsusf_usmc_marpat_d_engineer",
"rhsusf_usmc_marpat_d_rifleman_m590",
"rhsusf_usmc_marpat_wd_uav",
"rhsusf_usmc_marpat_wd_explosives",
"rhsusf_usmc_marpat_wd_engineer",
"rhsusf_usmc_marpat_wd_rifleman_m590",
"rhsusf_usmc_marpat_d_grenadier_m32",
"rhsusf_usmc_marpat_wd_grenadier_m32",
"rhsusf_usmc_recon_marpat_d_grenadier_m32",
"rhsusf_usmc_lar_marpat_d_grenadier_m32",
"rhsusf_usmc_recon_marpat_wd_grenadier_m32",
"rhsusf_usmc_lar_marpat_wd_grenadier_m32"
];

_unitsRifleman = [
"rhsusf_army_ucp_rifleman_m16",
"rhsusf_army_ucp_rifleman",
"rhsusf_army_ucp_rifleman_10th",
"rhsusf_army_ucp_rifleman_1stcav",
"rhsusf_army_ucp_riflemanl",
"rhsusf_army_ocp_rifleman",
"rhsusf_army_ocp_rifleman_10th",
"rhsusf_army_ocp_rifleman_1stcav",
"rhsusf_army_ucp_rifleman_arb_m16",
"rhsusf_army_ucp_arb_rifleman",
"rhsusf_army_ucp_rifleman_101st",
"rhsusf_army_ucp_rifleman_82nd",
"rhsusf_army_ocp_rifleman_m16",
"rhsusf_army_ocp_rifleman_101st",
"rhsusf_army_ocp_rifleman_82nd",
"rhsusf_army_ocp_rifleman_arb_m16",
"rhsusf_army_ocp_arb_rifleman",
"rhsusf_usmc_recon_marpat_wd_rifleman_fast",
"rhsusf_usmc_lar_marpat_wd_rifleman",
"rhsusf_usmc_marpat_wd_rifleman",
"rhsusf_usmc_recon_marpat_wd_rifleman",
"rhsusf_usmc_recon_marpat_d_rifleman",
"rhsusf_usmc_marpat_d_rifleman",
"rhsusf_usmc_recon_marpat_d_rifleman_fast",
"rhsusf_army_ucp_fso",
"rhsusf_army_ocp_fso",
"rhsusf_usmc_marpat_d_fso",
"rhsusf_usmc_marpat_wd_fso",
"rhsusf_infantry_socom_armysf_rifleman"
];

_unitsRiflemanLight = [
"rhsusf_army_ucp_rifleman_m4",
"rhsusf_army_ucp_jfo",
"rhsusf_army_ucp_officer",
"rhsusf_army_ocp_jfo",
"rhsusf_army_ucp_arb_riflemanl",
"rhsusf_army_ocp_officer",
"rhsusf_army_ocp_riflemanl",
"rhsusf_army_ocp_rifleman_m4",
"rhsusf_army_ocp_arb_riflemanl",
"rhsusf_socom_swcc_officer",
"rhsusf_socom_marsoc_jfo",
"rhsusf_socom_marsoc_jtac",
"rhsusf_socom_marsoc_elementleader",
"rhsusf_socom_marsoc_cso_light",
"rhsusf_socom_marsoc_cso_cqb",
"rhsusf_socom_marsoc_cso",
"rhsusf_usmc_marpat_wd_rifleman_light",
"rhsusf_usmc_marpat_wd_rifleman_m4",
"rhsusf_usmc_marpat_d_rifleman_m4",
"rhsusf_usmc_marpat_d_rifleman_light",
"rhsusf_usmc_recon_marpat_d_teamleader_lite",
"rhsusf_infantry_socom_armysf_base",
"rhsusf_usmc_lar_marpat_d_teamleader",
"rhsusf_usmc_lar_marpat_d_squadleader",
"rhsusf_usmc_lar_marpat_d_rifleman_light",
"rhsusf_usmc_lar_marpat_d_rifleman",
"rhsusf_usmc_marpat_d_jfo",
"rhsusf_usmc_marpat_d_officer",
"rhsusf_usmc_recon_marpat_d_rifleman_lite",
"rhsusf_usmc_recon_marpat_d_officer",
"rhsusf_usmc_marpat_wd_jfo",
"rhsusf_usmc_marpat_wd_officer",
"rhsusf_usmc_recon_marpat_wd_officer",
"rhsusf_usmc_lar_marpat_wd_rifleman_light",
"rhsusf_usmc_recon_marpat_wd_rifleman_lite",
"rhsusf_army_ucp_squadleader",
"rhsusf_army_ucp_teamleader",
"rhsusf_army_ucp_arb_teamleader",
"rhsusf_army_ucp_arb_squadleader",
"rhsusf_usmc_recon_marpat_d_teamleader",
"rhsusf_usmc_recon_marpat_wd_teamleader_lite",
"rhsusf_usmc_recon_marpat_wd_teamleader_fast",
"rhsusf_usmc_recon_marpat_d_teamleader_fast",
"rhsusf_usmc_lar_marpat_wd_teamleader",
"rhsusf_usmc_lar_marpat_wd_squadleader",
"rhsusf_socom_marsoc_teamchief",
"rhsusf_socom_marsoc_teamleader",
"rhsusf_usmc_marpat_d_teamleader",
"rhsusf_usmc_marpat_d_squadleader",
"rhsusf_usmc_marpat_wd_teamleader",
"rhsusf_usmc_marpat_wd_squadleader",
"rhsusf_army_ocp_arb_teamleader",
"rhsusf_army_ocp_arb_squadleader",
"rhsusf_army_ocp_teamleader",
"rhsusf_army_ocp_squadleader",
"rhsusf_usmc_recon_marpat_wd_teamleader"
];

_classMatch = ["rhsusf", (typeOf _unit)] call KK_fnc_inString;
if (!(_save) && (_classMatch)) then {unitcap = unitcap - 1; publicVariable "unitcap";};

if ((typeOf _unit) in _unitsGL) then {[_unit] call blufor_GL_loadout;};
if ((typeOf _unit) in _unitsAT) then {[_unit] call blufor_AT_loadout;};
if ((typeOf _unit) in _unitsAA) then {[_unit] call blufor_AA_loadout;};
if ((typeOf _unit) in _unitsAR) then {[_unit] call blufor_AR_loadout;};
if ((typeOf _unit) in _unitsMG) then {[_unit] call blufor_MG_loadout;};
if ((typeOf _unit) in _unitsMarksman) then {[_unit] call blufor_mark_loadout;};
if ((typeOf _unit) in _unitsSniper) then {[_unit] call blufor_sniper_loadout;};
if ((typeOf _unit) in _unitsCrew) then {[_unit] call blufor_crew_loadout;};
if ((typeOf _unit) in _unitsSpecial) then {[_unit] call blufor_spec_loadout;};
if ((typeOf _unit) in _unitsRifleman) then {[_unit] call blufor_rfl_loadout;};
if ((typeOf _unit) in _unitsRiflemanLight) then {[_unit] call blufor_light_loadout;};
